spring:
  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:mariadb://ws_study_db:3306/ws_study?useUnicode=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(WRdLmBtIsD+EB2q7ySFoFn8ofo9TGCPB)
    password: ENC(Xd7jenz6zLXrKL84T0Wzk3I3zMAIuw+l)

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: info
    org.hibernate.SQL: debug
