spring:
  datasource:
    hikari:
      pool-name: ws-study-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
